# Generated by Django 4.0.4 on 2022-06-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_user_delete_myproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
